# Configuration file for Consentus

workingDir: /tmp/consentus

zooKeeper:
  appRoot: /consentus
    
services:
  ActionCollector:
    ports:
      input: -1
    messageBufferSizes:
      recv: 1048576
      send: 1048576

  CanonicalState:
    ports:
      pub: 9000
      input: 9001
    messageBufferSizes:
      recv: 1048576
      pub: 1048576
    
  ClientHandler:
    ports:
      input: 10000
      pub: 10001
    messageBufferSizes:
      recv: 1048576
      routerSend: 1048576
      pub: 1048576
  
  CrowdHammerWorker:
    ports:
      pub: 12000
      routerRecv: 12001
    messageBufferSizes:
      routerRecv: 1048576
      routerSend: 1048576
            
crowdHammer:
  # the amount of time to test during each test execution phase
  testRunDurationInSeconds: 120