# Configuration file for Consentus

workingDir: /tmp/consentus

zooKeeper:
  appRoot: /consentus
    
services:
  CanonicalState:
    ports:
      pub: 9000
      sub: 9001
    
  ClientHandler:
    ports:
      input: 10000
      pub: 10001
            
  MetricListener:
    ports:
      input: 11000
            
crowdHammer:
  # the amount of time to test during each test execution phase
  testRunDurationInSeconds: 60